/* eslint no-unused-vars: 0 */

/**
 * auto-generated file
 * schema version: 20190324062939
 * This file was automatically generated by schema2type, which had some errors and converted sveral fields to camelcase.
 */
declare namespace schema {
  type ArtistRelease = {
    id: number;
    artist_id: number | null;
    releaseId: number | null;
  };

  type Artist = {
    id: number;
    name: string | null;
    bandcamp: string | null;
    facebook: string | null;
    spotify: string | null;
    soundcloud: string | null;
    instagram: string | null;
    created_at: string;
    updated_at: string;
    image_file_name: string | null;
    image_content_type: string | null;
    image_file_size: number | null;
    image_updated_at: string | null;
    slug: string | null;
    website: string | null;
    youtube: string | null;
    itunes: string | null;
    twitter: string | null;
    short_description: string | null;
  };

  type ArtistsRelease = {
    id: number;
    releaseId: number;
    artist_id: number;
  };

  type Embed = {
    id: number;
    content: string | null;
    created_at: string;
    updated_at: string;
  };

  type FriendlyIdSlug = {
    id: number;
    slug: string;
    sluggableId: number;
    sluggableType: string | null;
    scope: string | null;
    created_at: string | null;
  };

  type ReleaseEmbed = {
    id: number;
    releaseId: number | null;
    embedId: number | null;
    created_at: string;
    updated_at: string;
  };

  type Release = {
    id: number;
    artist_id: number | null;
    name: string | null;
    description: string | null;
    release_date: string | null;
    created_at: string;
    updated_at: string;
    image_file_name: string | null;
    image_content_type: string | null;
    image_file_size: number | null;
    image_updated_at: string | null;
    slug: string | null;
    buy: string | null;
    short_description: string | null;
    featured: boolean | null;
  };

  type Review = {
    id: number;
    name: string | null;
    releaseId: number | null;
    content: string | null;
    created_at: string;
    updated_at: string;
    slug: string | null;
    user_id: number | null;
    score: string | null;
  };

  // unused, we do not expose all of these strings
  type User = {
    id: number;
    provider: string;
    uid: string;
    encryptedPassword: string;
    resetPasswordToken: string | null;
    resetPasswordSentAt: string | null;
    allowPasswordChange: boolean | null;
    rememberCreatedAt: string | null;
    signInCount: number;
    currentSignInAt: string | null;
    lastSignInAt: string | null;
    currentSignInIp: string | null;
    lastSignInIp: string | null;
    confirmationToken: string | null;
    confirmedAt: string | null;
    confirmationSentAt: string | null;
    unconfirmedEmail: string | null;
    name: string | null;
    nickname: string | null;
    email: string | null;
    tokens: string | null;
    created_at: string;
    updated_at: string;
    isAdmin: boolean | null;
    image_file_name: string | null;
    image_content_type: string | null;
    image_file_size: number | null;
    image_updated_at: string | null;
  };
}
